# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# countsize2.py
# Created on: 2018-06-15 17:48:26.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
import csv

# Load required toolboxes
arcpy.ImportToolbox("C:/Software/arcgis/Desktop10.6/ArcToolbox/Toolboxes/Data Management Tools.tbx")

# Set the geoprocessing workspace
#arcpy.env.workspace = r"N:\ArcGIS\Default.gdb"
#arcpy.Delete_management ("in_memory")

# Local variables:
myset = ["C:/ArcGIS/myworkspace.gdb/bf_markham",
                "C:/ArcGIS/myworkspace.gdb/bf_london",
                "C:/ArcGIS/myworkspace.gdb/bf_waterloo",
                "C:/ArcGIS/myworkspace.gdb/bf_waterloo_region"]
buffertemp = "C:/ArcGIS/myworkspace.gdb/buffertemp"
multitemp = "C:/ArcGIS/myworkspace.gdb/multitemp"
simplifytemp = "C:/ArcGIS/myworkspace.gdb/simplifytemp"
dicetemp = "C:/ArcGIS/myworkspace.gdb/dicetemp"
dissolvetemp = "C:/ArcGIS/myworkspace.gdb/dissolvetemp"
studyareabuffered = "C:/ArcGIS/myworkspace.gdb/studyarea_merged_buffer"
RANGE_MIN = 10
RANGE_MAX = 111
RANGE_INTERVAL = 20
datatable = "plot.csv"

arcpy.Delete_management (buffertemp)
arcpy.Delete_management (multitemp)
arcpy.Delete_management (dicetemp)
arcpy.Delete_management (dissolvetemp)
with open(datatable, 'ab') as csvfile:
    mywriter=csv.writer(csvfile,delimiter=',',quotechar='"')
    for testarea in myset[3]:
        for Value in range(RANGE_MIN,RANGE_MAX,RANGE_INTERVAL):
            # Process: Buffer
            print "buffering"
            arcpy.Buffer_analysis(testarea, buffertemp, Value, "FULL", "ROUND", "NONE", "", "PLANAR")

            # Process: simplify
            #print "simplify"
            #arcpy.cartography.SimplifyPolygon(buffertemp, simplifytemp, POINT_REMOVE, 1)

            # Process: dice
            print "dicing"
            arcpy.Dice_management (buffertemp, dicetemp, 100)

            # Process: dissolve
            print "dissolving"
            arcpy.Dissolve_management(dicetemp, dissolvetemp)
                        
            # Process: Multipart To Singlepart
            print "parting" 
            arcpy.MultipartToSinglepart_management(dissolvetemp, multitemp)
    
            # Process: Get Count
            Row_Count = arcpy.GetCount_management(multitemp)

            #display results
            print Value
            print Row_Count[0]

            #append table
            mywriter.writerow([Value, Row_Count[0]])
    
            arcpy.Delete_management (buffertemp)
            arcpy.Delete_management (multitemp)
            arcpy.Delete_management (dicetemp)
            arcpy.Delete_management (dissolvetemp)
        mywriter.writerow('')
        
